### ISSUE TITLE
Bubblepoint pressure upper limit too low

### ISSUE THREAD

**Issue by coreymckeon** [kwellis/woffl#5]
Some of the constraints on pvt seem a bit too limiting. The oil I'm using is a 3100-3200 bubble point pressure, for example. Is the 3000 psi limit sourced from a recommended range for the correlations being utilized? Can we up this to 3500 or 4000?

**Comment by kwellis** [comment]
I'll take a look next week at some of the correlations and see. I believe some of the constraints are fairly arbitrary, but I wanted to prevent people from defining volatile oils as black oils.

**Comment by kwellis** [comment]
I would rather not make the change. None of the oil's that are currently being modeled require this upper bound.
